### ISSUE TITLE
Duplicate warning

### ISSUE THREAD

**Issue by axelson** [hauleth/mix_machine#9]
Is there a way to avoid the duplicate warning?

![Screen Shot 2021-11-26 at 4 48 12 PM](https://user-images.githubusercontent.com/9973/143666062-234ca44a-f83b-435c-adb5-e80bebebc48a.png)

I think one of the warnings might come directly from GitHub parsing the output automatically but I'm not 100% sure.

Here's the PR that surfaced that warning: https://github.com/axelson/password-validator/pull/21

**Comment by hauleth** [comment]
Yes, one of the result is from automatic GitHub Actions parsing of the compilation output and I do not know how to control that. The second one is coming from SARIF report upload. I do not know if there is any way to deduplicate these. Leaving it as open for now.

**Comment by hauleth** [comment]
Created topic on GitHub Community forum

https://github.community/t/duplicated-entries-form-automatic-output-parsing-and-sarif-reporting/214945

**Comment by hauleth** [comment]
Closed via https://github.com/erlef/setup-beam/issues/77
